### ISSUE TITLE
COMSOL 2D mesh

### ISSUE THREAD

**Issue by EMinsight** [awslabs/palace#102]
Hi @sebastiangrimberg,

I get 2D mesh from COMSOL and import it to palace. It failed while reading the mesh.

Here is the error:

```
Verification failed: (sdim == 3) is false:
 --> COMSOL mesh nodes are required to be in 2D or 3D space!
 ... in function: void palace::mesh::ConvertMeshComsol(const string&, std::ostream&)
```

The mesh converter won't change 2D point to 3D point?

**Comment by sebastiangrimberg** [comment]
Hi @EMinsight, sorry for the delay here. There are two points to answering this question for you:

- First, yes this indeed appears to be a bug, see #104 for a fix. The 2D vertex coordinates should be converted automatically to 3D for the 2D Gmsh mesh.
- Second, Palace at this point does not really have support 2D problems. It may work for electrostatics, but the formulations for all other problems really make the assumption that the computational domain is 3D. Solving the full-wave Maxwell's equations in a 2D domain needs special treatment.

Regarding the second point, there is some functionality to still solve 2D problems in a specific manner. The [wave port](https://awslabs.github.io/palace/stable/guide/boundaries/#Lumped-and-wave-port-excitation) functionality available for frequency domain driven simulations will solve the correct 2D boundary mode problem on given ports in order to determine a mode shape and propagation constant to use in exciting the 3D model and calculating scattering parameters. So, if you're only interested in 2D analysis of a wave guide or transmission line, for example, you can create a 2D mesh and extrude it some small amount, and select the cross section as a wave port to compute the boundary mode. I hope this makes sense, it's a bit of a hack on top of the current 3D-focused functionality but may allow you to achieve what you want depending on the problem you are trying to solve.

**Comment by EMinsight** [comment]
Thanks. I see your point.

BTW, COMSOL supports three modes of 2D problems (in plane, out of plane and full vector).

**Comment by sebastiangrimberg** [comment]
> BTW, COMSOL supports three modes of 2D problems (in plane, out of plane and full vector).

That's correct, and could be a possible addition to Palace in the future if that is something which would be useful to users. The current thinking for Palace is that if we can make the full 3D simulation highly performant and scalable, then the usefulness of 2D simulations becomes less since you can just go ahead and simulate the actual 3D structure without worrying too much about cost.
