### ISSUE TITLE
Can Palace use SLEPc?

### ISSUE THREAD

**Issue by lcheng9** [awslabs/palace#139]
Hi Palace Team, 

When preprocessor macros PALACE_WITH_SLEPC and PETSC_USE_COMPLEX are defined. The dependent library MFEM complains for "MFEM does not work with PETSc compiled with complex numbers support", see mfem/linalg/petsc.hpp. 

Does it mean that SLEPc cannot be used in Palace, and use ARPACK instead? Thank you.

**Comment by sebastiangrimberg** [comment]
Hi @lcheng9, yes Palace can use SLEPc. You should not be linking to an MFEM build which has been configured to use PETSc, however. Palace should always build it's own version of MFEM which is never compiled with `MFEM_USE_PETSC` and Palace links directly to SLEPc rather than using the MFEM interface (which only supports real-valued scalars).

**Comment by sebastiangrimberg** [comment]
Is there a reason you are using an external MFEM build and not just using the existing MFEM which is built as part of the Palace build system? I worry this might cause problems as the intended usage is for Palace to always built it's own MFEM. This is true for the Spack build as well as builds from source using CMake.

**Comment by sebastiangrimberg** [comment]
Oh I see, that's an interesting approach. I suppose as long as you are including the patches to MFEM as Palace expects everything should work fine. I'll close this for now, thanks for your interest!
