### ISSUE TITLE
Error in build palace from source

### ISSUE THREAD

**Issue by huangyb2** [awslabs/palace#289]
Hi! 
I want to build palace-0.13.0 form soure, but it always failed cause the internet error. I think that if I can download the all third-party packages by mannual and then compile by myself would help to address this problem.But i don't know how to revise the CMakeLists.txt.

Any help or advise will be appreciate!

**Comment by hughcars** [comment]
Hi @huangyb2,

The decision was taken to build Palace's dependencies directly as part of the Palace build process because a) there are many dependencies, many optional, so requiring a user to build externally would open a lot of space for configuration errors b) often we need specific commits from the various repositories as fixes and bugs appear and c) we apply various patches to the dependencies. Orchestrating this outside of the build system would be extremely cumbersome for both developers and users, so we decided to avoid it and roll everything into a controllable build system. As such there is no plan at present to support externally built dependencies in the way you describe. 

If you post the particular error message, maybe I could be of more help.

**Comment by sebastiangrimberg** [comment]
I might also suggest trying to build with Spack, which may have better support for configuring and building the Palace dependencies on your system.

**Comment by huangyb2** [comment]
Hi@sebastiangrimberg ,
Thanks your reply! I did buid palace-0.12.0 by Spack, and it is very convinient. When build palace-0.13.0 from soure, error message as fellow: 
![50faa31c01e7705b08da7a1bf88d38a7](https://github.com/user-attachments/assets/fb379a40-6dc7-4323-ac19-c4ffc7fea7af)

**Comment by huangyb2** [comment]
Hi@hughcars
I notice that most the third-party dependencies got by git clone.And I have build palace-0.12.0 by Spack.Whether it is possible to link to these dependecies build form Spack, when I build palace-0.13.0 from source？

**Comment by hughcars** [comment]
Hi @huangyb2, I do not know. In general `spack` is pretty intelligent in reusing relevant builds of dependencies if they already exist in the cache. So if `spack` is rebuilding, that suggests that there is a difference in the dependency and as such it is unable to reuse. I would suggest referring to the spack documentation if you need to understand more about the spack build/cache system.

**Comment by huangyb2** [comment]
Hi@sebastiangrimberg,@hughcars ,Thanks your sugegests.I successfully solve this problem. And palace-0.13.0 can both be installed by linking to local dependencies and linking dependenices to that 3-parties installed by spack.
