### ISSUE TITLE
Far-field radiation patterns can be calculated in the example/cpw?

### ISSUE THREAD

**Issue by zhuyue14** [awslabs/palace#294]

**Comment by hughcars** [comment]
Hi @zhuyue14, by farfield do you mean as in some boundary at an infinite distance away? Or on the boundary of the model? Palace doesn't have a Sommerfeld radiation boundary condition, instead we mainly use the absorbing boundary condition which is an approximation but we've had reasonable results with thus far. Additionally, are you wanting functional outputs (i.e. integrated quantities over the boundary) or to visualize the field? The boundary visualization can be done with paraview.

**Comment by zhuyue14** [comment]
Hi @hughcars ,In most antenna applications, farfield  mean as in some boundary at an infinite distance away.Usually, we need to perform near-to-far field transformations, which require the electric field E and magnetic field H on the virtual boundaries of the near-field enclosure, or equivalent surface current densities. Additionally, what I want is the functionality to output integrated quantities over the boundaries.

**Comment by hughcars** [comment]
Hi @zhuyue14, we do not currently have any transformation to a notional farfield boundary. Palace has first and second order absorbing boundary conditions (the second order requires the "farfield" be notionally spherical to really recover the higher order accuracy, but that shouldn't be an issue for an antenna) which you can apply to the near-field boundary. Using those boundary conditions, if you are looking only for integral over the whole boundary, you are essentially done, as you can select the integrals available in the documentation. For more details on the absorbing boundary conditions, I would suggest [`the textbook of Jian-Ming Jin`](https://www.wiley.com/en-it/The+Finite+Element+Method+in+Electromagnetics%2C+3rd+Edition-p-9781118571361) which is very helpful.

We do not currently have perfectly matched layers which would be the ideal way to handle this, though we would like to implement them, we have not had the resources to do so yet. If you are interested in doing so we would welcome the contribution. 

If choose the absorbing boundary conditions and you are looking for angular resolution of your integrals, then you might have to do something more sophisticated, whereby you partition the boundary into a selection of boundary attributes rather than just one. You then assign all these attributes to the boundary condition, but perform the integrals for each separately in postprocessing, this would achieve any angular resolution you are prepared to set up on the boundary.

**Comment by zhuyue14** [comment]
Thank you for your suggestions; your response has been very helpful to me.

**Comment by sebastiangrimberg** [comment]
Hi @zhuyue14, I saw your issue and wanted to add a few comments. While Hugh provided discussion of boundary conditions in Palace, I think the near-to-far field transformation you are interested in is really a postprocessing operation which is independent of model boundary conditions (though typically you would always have some sort of absorbing boundary for these types of models). There a closed-form formulas to compute the far-field fields as a function of the near-field field which your model computes in the computational domain. Stratton-Chu comes to mind as one of these and I believe it shouldn't be too hard to find references for the formula. I'm pretty sure Jin which Hugh referenced has a section on this. Then you can do various postprocessing (visualization or otherwise) on the postprocessed far-fields.

I think this would be a valuable addition to Palace for antenna and similar applications. It should fit well within the current postprocessing framework and would just require the user specifying a (spherical?) surface on which to sample the computed near-fields which are used to then compute the far-fields.
