### ISSUE TITLE
Option to pass either a functional form or a pre-computed conductivity/resistivity array to estimate Ohmic losses

### ISSUE THREAD

**Issue by ankagrwl** [awslabs/palace#59]
*Description: For metals such as Copper at high frequencies (~10 GHz), the conductivity is a function (polynomial) of frequency due to the anomalous skin depth effect. It would be great to add this feature to compute accurate losses at such high frequencies.*

*[Reference](https://cds.cern.ch/record/2718002/files/ASE_Mathematica_05.04.pdf)*

**Comment by sebastiangrimberg** [comment]
Hi @ankagrwl, I believe this might already be implemented as the `config["Boundaries"]["Conductivity"]` option: https://awslabs.github.io/palace/stable/config/boundaries/#boundaries[%22Conductivity%22].

I realize the documentation for this option is quite poor, and I think there should be a section in the documentation reference (https://awslabs.github.io/palace/stable/reference/) addressing this BC. For now, you can check out the implementation here to see that it fits your needs: https://github.com/awslabs/palace/blob/main/palace/models/surfaceconductivityoperator.cpp#L139.

If there are any changes to the current model, or options we could add in order to address the `\delta << \ell` case, it would be great if you could suggest changes or open a PR. Additionally I would greatly welcome any contributions you might propose to the docs to make this more clear. Thanks again!

**Comment by sebastiangrimberg** [comment]
This will be resolved by an upcoming update to the docs.
