### ISSUE TITLE
Cannot get full S matrix in Driven simulations

### ISSUE THREAD

**Issue by nikosavola** [awslabs/palace#81]
*Description: A clear and concise description of what the bug is.*

Not sure if I'm understanding something wrong, but it appears when running a Driven simulation such as the CPW example, if one wants to find the full $4\times4$ scattering matrix you cannot currently set all the boundaries to have `"Excitation": true` and get the full matrix. Instead, I get nothing out. Is this a bug?

*To reproduce: Please provide minimal example that reproduces the error. For existing
examples, please provide a link.*

Add `"Excitation": true` to, for example, other LumpedPorts in https://github.com/awslabs/palace/blob/42ec49d1f9150921cc786850df33b719bb8e0e56/examples/cpw/cpw_lumped_adaptive.json

*Error message: Paste the complete error message or log, if applicable.*

*Environment: Any environment details, such as operating system, compiler, etc.*
Palace tag v0.11.2 in singularity image

**Comment by sebastiangrimberg** [comment]
Indeed this is not really a bug but is the expected behavior. If you look at the logic [here](https://github.com/awslabs/palace/blob/main/palace/drivers/drivensolver.cpp#L613), you will see that if more than one port is specified for excitation, S-parameters are not computed as they don't make much sense in this case. Palace is still going to  compute the electromagnetic response of the system to the excitation on all 4 ports *at the same time*, which is why the simulation does not error and you still get other outputs.

To produce a full scattering matrix as you desire, you need to run one simulation per column of the scattering matrix you want to postprocess. Fortunately these can be done in "embarrassingly parallel" fashion (you can compute each column of the scattering matrix independently, so can launch Palace 4 times non-interactively to compute the result).

Hopefully this clarifies your observation. I suppose this should be clarified in the documentation, probably [here](https://awslabs.github.io/palace/stable/guide/problem/#Driven-problems-in-the-frequency-domain).

**Comment by nikosavola** [comment]
I see, thanks for the explanation!

I feel like this would be nice to have in Palace side s.t. just one call of `palace` does the 4 different simulations and outputs the 4x4 matrix. I guess there is a way to somehow do this efficiently?

**Comment by sebastiangrimberg** [comment]
This is really something I like to give users control over, since there isn't really much optimization to be done on the Palace side in terms of doing it more "efficiently" than from the user. It's really easy to script. In Python, for example:

```
import json
import os
import subprocess

# Base configuration file
config_path = "config.json"

for i in range(4):
    # Prepare configuration file for simulation
    with open(config_path, "r") as f:
        config_json = json.loads(f.read())
    for port in config_json["Boundaries"]["LumpedPort"]:
        port["Excitation"] = (1+i == port["Index"])

    # Write new config file
    config_path_i = os.path.splitext(config_path)[0] + f"-{1+i}.json"
    with open(config_path_i, "w") as f:
        f.write(json.dumps(config_json))

    # Run Palace simulation
    subprocess.run(["palace", "-np", 4, config_path_i)
```

**Comment by sebastiangrimberg** [comment]
I will mark this as closed for now. Feel free to reopen and let us know if you run into any issues or have any further suggestions on how to improve this workflow!
