### ISSUE TITLE
Built Singularity image not visible in packages

### ISSUE THREAD

**Issue by nikosavola** [awslabs/palace#83]
*Description: A clear and concise description of what the bug is.*

The Singularity image built in GitHub Actions is not visible in Packages

![image](https://github.com/awslabs/palace/assets/7860886/2997d17a-cc63-4706-8786-f67595acd5ce)

I guess this is due to permission settings in the repo? Seems like the action is pushing to the correct location

![image](https://github.com/awslabs/palace/assets/7860886/3eaf62c0-ef1c-4fdd-85ae-266617652945)

*To reproduce: Please provide minimal example that reproduces the error. For existing
examples, please provide a link.*

Go to https://github.com/orgs/awslabs/packages?repo_name=palace

**Comment by sebastiangrimberg** [comment]
Hi @nikosavola, indeed it looks like the package is currently marked as private visibility. We will see what we can do about changing the visibility to public.

**Comment by sebastiangrimberg** [comment]
Hi @nikosavola, so I have some information on this to report. Making the prebuilt image available for download counts as a distribution not only of Palace, but also it's entire dependency stack including the OS chosen in the image and various vendor installs there. This means there are larger implications for licensing than just distributing source for Palace or a Singularity image recipe. In order to distribute the Singularity image itself, we will have to go through a review process in order to ensure compliance, and this will likely require some further changes to the image to ensure everything checks out legally.

Since this will require some effort on our part and right now we don't really have the bandwidth to manage distribution support tasks like this (hence why we push Spack on users so strongly!), I think the best course of action is to remove the CI job which pushes the image to the package registry and update the documentation accordingly in order to avoid confusing users. For now we will rely on users building and hosting their own Singularity images using the recipe and instructions in `singularity/` in the Palace repository, and thus no functionality is lost. If eventually we want to get into the game of vending Palace as a precompiled package, then we can revisit the image hosting route.

Sorry for any inconvenience this causes you but hope you can understand. I'll close this issue for now and follow up shortly with a PR updating the CI job and documentation. Feel free to follow up here with any comments or reopen as necessary.

**Comment by nikosavola** [comment]
It's a shame but I understand. The action points sound good to me.
